#!/usr/bin/env bash
# Reproduces the firewall state an Oracle Ubuntu image arrives in: the full
# default ruleset loaded into the running chains AND persisted to
# /etc/iptables/rules.v4.
#
# The whole ruleset is loaded via iptables-restore, not just the trailing
# REJECT. Oracle's ruleset accepts RELATED,ESTABLISHED before it rejects; a
# lone REJECT would also drop DNS replies and break the container's network,
# which is not what a real VM does.
set -euo pipefail

mkdir -p /etc/iptables
cat > /etc/iptables/rules.v4 <<'EOF'
# Generated by iptables-save (Oracle default Ubuntu image)
*filter
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
-A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
-A INPUT -p icmp -j ACCEPT
-A INPUT -i lo -j ACCEPT
-A INPUT -p tcp -m state --state NEW -m tcp --dport 22 -j ACCEPT
-A INPUT -j REJECT --reject-with icmp-host-prohibited
-A FORWARD -j REJECT --reject-with icmp-host-prohibited
COMMIT
EOF

iptables-restore < /etc/iptables/rules.v4

echo "seeded Oracle-style firewall state"
echo "--- running INPUT ---"
iptables -S INPUT
echo "persisted REJECT lines: $(grep -c -- '-j REJECT --reject-with icmp-host-prohibited' /etc/iptables/rules.v4)"

# Sanity: outbound DNS must still work, exactly as it does on a real VM.
if getent ahostsv4 archive.ubuntu.com >/dev/null 2>&1; then
  echo "DNS after seeding: OK"
else
  echo "DNS after seeding: BROKEN — the seed is wrong, not the script under test" >&2
  exit 1
fi
